.TH "BASS_DX8_GARGLE" 3 "Sat Aug 31 2013" "RecordStudio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BASS_DX8_GARGLE \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DWORD \fBdwRateHz\fP"
.br
.ti -1c
.RI "DWORD \fBdwWaveShape\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 799 of file bass\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RecordStudio from the source code\&.
