.TH "BASS_FILEPROCS" 3 "Sat Aug 31 2013" "RecordStudio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BASS_FILEPROCS \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FILECLOSEPROC * \fBclose\fP"
.br
.ti -1c
.RI "FILELENPROC * \fBlength\fP"
.br
.ti -1c
.RI "FILEREADPROC * \fBread\fP"
.br
.ti -1c
.RI "FILESEEKPROC * \fBseek\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 475 of file bass\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RecordStudio from the source code\&.
