.TH "BASS_DX8_COMPRESSOR" 3 "Sat Aug 31 2013" "RecordStudio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BASS_DX8_COMPRESSOR \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBfGain\fP"
.br
.ti -1c
.RI "float \fBfAttack\fP"
.br
.ti -1c
.RI "float \fBfRelease\fP"
.br
.ti -1c
.RI "float \fBfThreshold\fP"
.br
.ti -1c
.RI "float \fBfRatio\fP"
.br
.ti -1c
.RI "float \fBfPredelay\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 764 of file bass\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RecordStudio from the source code\&.
