.TH "BASS_DX8_REVERB" 3 "Sat Aug 31 2013" "RecordStudio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BASS_DX8_REVERB \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBfInGain\fP"
.br
.ti -1c
.RI "float \fBfReverbMix\fP"
.br
.ti -1c
.RI "float \fBfReverbTime\fP"
.br
.ti -1c
.RI "float \fBfHighFreqRTRatio\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 825 of file bass\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RecordStudio from the source code\&.
