.TH "BASS_PLUGINFORM" 3 "Sat Aug 31 2013" "RecordStudio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BASS_PLUGINFORM \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DWORD \fBctype\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBexts\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 348 of file bass\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RecordStudio from the source code\&.
