.TH "BASS_INFO" 3 "Sat Aug 31 2013" "RecordStudio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BASS_INFO \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DWORD \fBflags\fP"
.br
.ti -1c
.RI "DWORD \fBhwsize\fP"
.br
.ti -1c
.RI "DWORD \fBhwfree\fP"
.br
.ti -1c
.RI "DWORD \fBfreesam\fP"
.br
.ti -1c
.RI "DWORD \fBfree3d\fP"
.br
.ti -1c
.RI "DWORD \fBminrate\fP"
.br
.ti -1c
.RI "DWORD \fBmaxrate\fP"
.br
.ti -1c
.RI "BOOL \fBeax\fP"
.br
.ti -1c
.RI "DWORD \fBminbuf\fP"
.br
.ti -1c
.RI "DWORD \fBdsver\fP"
.br
.ti -1c
.RI "DWORD \fBlatency\fP"
.br
.ti -1c
.RI "DWORD \fBinitflags\fP"
.br
.ti -1c
.RI "DWORD \fBspeakers\fP"
.br
.ti -1c
.RI "DWORD \fBfreq\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 167 of file bass\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RecordStudio from the source code\&.
