.TH "MSMasterCmp Directory Reference" 3 "Sat Aug 31 2013" "RecordStudio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSMasterCmp Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbass\&.h\fP"
.br
.ti -1c
.RI "file \fBbassmix\&.h\fP"
.br
.ti -1c
.RI "file \fBmsmastercmp\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmsmastercmp\&.h\fP"
.br
.ti -1c
.RI "file \fBMSMasterCmp_global\&.h\fP"
.br
.ti -1c
.RI "file \fBMSMasterError\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmsmastererror\&.h\fP"
.br
.in -1c
