.TH "DAWComponents Directory Reference" 3 "Sat Aug 31 2013" "RecordStudio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DAWComponents Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbass\&.h\fP"
.br
.ti -1c
.RI "file \fBDAWComponents_global\&.h\fP"
.br
.ti -1c
.RI "file \fBdawerror\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdawerror\&.h\fP"
.br
.ti -1c
.RI "file \fBdawinput\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdawinput\&.h\fP"
.br
.ti -1c
.RI "file \fBfileinput\&.cpp\fP"
.br
.ti -1c
.RI "file \fBfileinput\&.h\fP"
.br
.in -1c
