.TH "DAWInputs::DAWError" 3 "Sat Aug 31 2013" "RecordStudio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DAWInputs::DAWError \- 
.PP
The \fBDAWError\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dawerror\&.h>\fP
.PP
Inherits QException\&.
.SH "Detailed Description"
.PP 
The \fBDAWError\fP class\&. 
.PP
Definition at line 11 of file dawerror\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RecordStudio from the source code\&.
