.TH "DAWInputs::InputBase" 3 "Sat Aug 31 2013" "RecordStudio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DAWInputs::InputBase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.PP
Inherited by \fBDAWInputs::FileInput\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetError\fP (bool error)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const DWORD \fBgetInputHandle\fP ()"
.br
.ti -1c
.RI "void \fBsetInputHandle\fP (DWORD handle)"
.br
.ti -1c
.RI "bool \fBgetErrorState\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file dawinput\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RecordStudio from the source code\&.
