.TH "tWAVEFORMATEX" 3 "Sat Aug 31 2013" "RecordStudio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tWAVEFORMATEX \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "WORD \fBwFormatTag\fP"
.br
.ti -1c
.RI "WORD \fBnChannels\fP"
.br
.ti -1c
.RI "DWORD \fBnSamplesPerSec\fP"
.br
.ti -1c
.RI "DWORD \fBnAvgBytesPerSec\fP"
.br
.ti -1c
.RI "WORD \fBnBlockAlign\fP"
.br
.ti -1c
.RI "WORD \fBwBitsPerSample\fP"
.br
.ti -1c
.RI "WORD \fBcbSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 702 of file bass\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RecordStudio from the source code\&.
